### ISSUE TITLE
.schema <table>; returns nothing

### ISSUE THREAD

**Issue by thewhitetulip** [smparkes/sqlite#1]
When the command .schema <table>; is executed with a semi colon at the end it should accept the .schema operator, but it doesn't and shows empty records, it should either return some error message or strip the semicolon

**Comment by smparkes** [comment]
This mirror isn't maintained anymore. I'm not sure where the canonical sqlite source is at this point.

**Comment by thewhitetulip** [comment]
I had assumed this was an official email, I wanted to raise a bug, I have emailed on their dev mailing list though
